### PR TITLE
Update screenshots

### LINKED ISSUE #25: Update screenshots
Once PR are merged #21, #22, #23, #24, screenshots will need to be updated.

### PR DESCRIPTION
**Pull request by t20100**
Closes #25

### CODE REVIEW

**Review by loichuder — COMMENTED** [review]
I don't like so much having the screenshots in the repo and then packages.

What is the added value in your mind ?

**Comment by t20100** [comment]
The pros is that the documentation is standalone in the repo.
The screenshots are not packaged in the wheel which is what is used to install the package.

But, I don't know what happens when uploading to pypi, so maybe it's an issue.

**Comment by t20100** [comment]
It does not work when uploaded to pypi.org, so I'll use links.

**Comment by t20100** [comment]
Screenshots updated using links instead

**Review by loichuder — APPROVED** [review]

**Pull request merged**
